### ISSUE TITLE
Increase the H2GIS tests

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis-geotools#35]
We must increase the battery of tests to be conform with the tests  available in GeoTools.

See : https://github.com/geotools/geotools/wiki/H2-upgrade-notes

@aaime @jodygarnett @ianturton

**Comment by aaime** [comment]
@ebocher that wiki page is 4 years old, mind, but yes, code coverage should be increased.
It would also be nice to have a basic store with minimal dependencies (I think with H2 v2 one could write a basic, working store with no external dependencies at all), I see H2GIS adds quite a bit of jars to depend onto, are they all required?

**Comment by ebocher** [comment]
Hi @aaime 


> @ebocher that wiki page is 4 years old, mind, but yes, code coverage should be increased.

oupps.

> It would also be nice to have a basic store with minimal dependencies (I think with H2 v2 one could write a basic, working store with no external dependencies at all), I see H2GIS adds quite a bit of jars to depend onto, are they all required?

Here the H2GIS list of deps :  

jackson-core -> to parse geojson used in gt-main  [Required]

jts-core -> also in gt-main  [Required]

cts -> used by H2GIS to perform transformation  [Required]

commons-compress -> used to read zip and gz files. It seems not used by gt.  [Required] I don't if we can remove it easly.

poly2tri -> library to expose constrained and delaunay triangulations functions.  We will replace it by TinFour in few weeks (https://github.com/gwlucastrig/Tinfour). A fast and robust triangulation library. [Required]

h2gis-network -> graph network analysis based on jna and jgrapht libs. [Not required]

h2gis-functions-osgi -> expose function as OSGI service [Not required]

postgis-jts -> wrapper to link a postgis table to an H2GIS  database.  [Not required]

postgis-jts-osgi -> expose postgis-jts as an osgi datasource [Not required]

Note : there is an issue to remove compendium dependency

**Comment by ebocher** [comment]
I let @nicolas-f  answer on the osgi part as he will be more precise than me ;-)

**Comment by nicolas-f** [comment]
The OSGi dependency should not be there, it will be removed
https://github.com/orbisgis/h2gis/pull/1291#issuecomment-1066973595

**Comment by ebocher** [comment]
@aaime 
Done H2GIS is now aligned with geotools-jdbc unit tests
Thanks @SPalominos
