### ISSUE TITLE
Cover postCreateTable method in unit tests

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis-geotools#5]
Follow up of this thread

http://h2gis.1099522.n5.nabble.com/Possible-bug-in-h2gis-geotools-td96.html

We have here the PostGIS syntax not the H2GIS one:
https://github.com/orbisgis/h2gis-geotools/blob/master/src/main/java/org/h2gis/geotools/H2GISDialect.java#L525

H2GIS currently does not support providing the SRID constraint in the type.

**Comment by ebocher** [comment]
hoops. 
Good catch!
I will have a look in the next 2 weeks

**Comment by ebocher** [comment]
Thanks I will fix it

**Comment by ebocher** [comment]
Fix in master 0.0.2-SNAPSHOT
